# Generated by Django 5.2.11 on 2026-03-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonreception',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonreception',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lignebonreception',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit'),
        ),
    ]
