# Generated by Django 5.2.11 on 2026-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_bonreception_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebonreception',
            name='prix_ht',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Achat'),
        ),
        migrations.AlterField(
            model_name='lignedemande',
            name='prix_ht',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Achat'),
        ),
        migrations.AlterField(
            model_name='lignefactureachat',
            name='prix_ht',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Achat'),
        ),
    ]
