# Generated by Django 5.2.11 on 2026-03-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
    ]
