# Generated by Django 5.2.11 on 2026-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='adresse_client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='email_client',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='facture',
            name='mf_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facture',
            name='telephone_client',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
