# Generated by Django 5.2.11 on 2026-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_facture_adresse_client_facture_email_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total_rem',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='taux_rem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
