# Generated by Django 5.2.11 on 2026-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_facture_total_rem_lignefacture_taux_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='base_tva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
