# Generated by Django 5.2.11 on 2026-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
    ]
