# Generated by Django 6.0.3 on 2026-03-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('reglements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('observation', models.TextField(blank=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='comptes.compte')),
            ],
        ),
    ]
