# Generated by Django 6.0.3 on 2026-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0002_mouvementcompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcompte',
            name='origine',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
