# Generated by Django 5.2.11 on 2026-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=4)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
