# Generated by Django 5.2.11 on 2026-03-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='p_achat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Prix Achat'),
        ),
    ]
